print ('&&   Calculater Program   &&')
first=float(input('Enter the first number '))
second=float(input('Enter the second number '))
print('')
print('adding + = '+str(first+second))
print('subsract - = '+str(first-second))
print('multiply  = '+str(firstsecond))
print('divide  = '+str(firstsecond))
print('modulus % = '+str(first%second))
print('We Hope You Have Happy Day ^_^')